Updated to 8.0.0-alpha.644
Particular/NServiceBus.AzureStorageQueues pull request #468
Opened 2020-10-29 14:23 UTC by ramonsmits

- Fix breaking changes related to removal of timeout manager
- Marked code related to non-durable messaging with TODO's
- Fix change related to AT persistence configuration

2020-10-30 19:15 UTC, bording requested changes

2020-10-30 19:15 UTC, bording commented on src/Transport/obsoletes.cs
> +    /// <summary>Configures native delayed delivery.</summary>
XML comments should be removed from obsoletes. The file can be marked with `#pragma warning disable 1591` / `#pragma warning restore 1591`

2020-10-30 19:15 UTC, bording commented on src/Transport/Config/DelayedDeliverySettings.cs
>              this.GetSettings().Set(WellKnownConfigurationKeys.DelayedDelivery.DisableDelayedDelivery, true);
This setting and the test about throwing when it's disable means there is more work to done here. It's not the transports responsibility to throw in this scenario now. Instead, we need to alter the `DeliveryConstraints` in  `AzureStorageQueueInfrastructure` when this is called to inform core and let it handle things.

2020-10-30 19:15 UTC, bording commented on src/AcceptanceTests/Sending/When_delaying_messages_and_delayed_delivery_is_disabled.cs
> -                    delayedDelivery.DisableTimeoutManager();
I suspect this entire test can be removed once we fix up the `DisableDelayedDelivery` API.

2020-11-02 16:20 UTC, ramonsmits commented on src/AcceptanceTests/Sending/When_delaying_messages_and_delayed_delivery_is_disabled.cs
> -                    delayedDelivery.DisableTimeoutManager();
@bording what do you mean, that there will be a test part of the core AT's to replace this?

2020-11-03 20:45 UTC, bording approved these changes

2020-11-03 20:45 UTC, merged