GitHubSync update - release-9.0
Particular/NServiceBus.AzureStorageQueues pull request #509
Opened 2021-01-15 19:06 UTC by particularbot6

This is an automated synchronization PR.

The following source template repositories were used:
* particular/RepoStandards

2021-01-15 22:58 UTC, bording requested changes

2021-01-15 22:58 UTC, bording commented on src/AcceptanceTests/Sending/When_dispatching_fails.cs
> +            { throw new Exception("Fail on proxy"); };
Why did this change?

2021-01-15 22:58 UTC, bording commented on src/Transport/DelayDelivery/SimpleJSON.cs
> -    [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
Same comment about SimpleJson as the `master` PR. Let's revert the changes here.

2021-01-15 23:04 UTC, SeanFeldman commented on src/AcceptanceTests/Sending/When_dispatching_fails.cs
> +            { throw new Exception("Fail on proxy"); };
Fantastic question. Changes were applied to the solution so not sure why this specific line has changed. I can revert it.

2021-01-15 23:41 UTC, bording commented on src/Transport/DelayDelivery/SimpleJSON.g.cs
> +#pragma warning disable IDE0065 // Misplaced using directive
You just renamed the file, you didn't revert the changes to it.

2021-01-18 18:53 UTC, SeanFeldman commented on src/Transport/DelayDelivery/SimpleJSON.cs
> -    [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
Done

2021-01-18 18:57 UTC, SeanFeldman commented on src/AcceptanceTests/Sending/When_dispatching_fails.cs
> +            { throw new Exception("Fail on proxy"); };
BTW, this is why it was changed: https://builds.particular.net/buildConfiguration/NServiceBus_Transports_NServiceBusAzureStorageQueues_1Compile/706894?

2021-01-18 22:19 UTC, bording approved these changes

2021-01-18 22:22 UTC, merged