New transport seam
Particular/NServiceBus.AzureStorageQueues pull request #510
Opened 2021-01-23 09:44 UTC by mauroservienti

2021-02-01 12:04 UTC, tmasternak requested changes

2021-02-01 12:04 UTC, tmasternak commented on src/Transport/DelayDelivery/DelayedMessageEntity.cs
> +            return new UnicastTransportOperation(new OutgoingMessage(MessageId, Deserialize<Dictionary<string, string>>(Headers), Body), Destination, new DispatchProperties());
I think that passing empty `DispatchProperites`is fine. We can't have TTBR on a delayed message. 

Maybe we should do that validation in `DispatchProperties`?

2021-02-01 15:41 UTC, mauroservienti commented on src/Transport/AzureStorageQueueTransport.cs
> +        public AzureStorageQueueTransport(string connectionString, bool disableNativeDelayedDeliveries = false)
Yeah, makes sense

2021-02-01 15:42 UTC, mauroservienti commented on src/Transport/AzureStorageQueueTransport.cs
> +                delayedMessagesStorageTable = await EnsureNativeDelayedDeliveryTable(
Agreed, I'll make a note to myself that the table schema should be probably documented.

2021-02-01 16:13 UTC, mauroservienti commented on src/Transport/AzureStorageQueueTransport.cs
> +        public int? ReceiverBatchSize
I made a mistake, it has to be null by default and the default value entirely removed.

2021-02-02 14:18 UTC, mauroservienti commented on src/Transport/DelayDelivery/DelayedMessageEntity.cs
> +            return new UnicastTransportOperation(new OutgoingMessage(MessageId, Deserialize<Dictionary<string, string>>(Headers), Body), Destination, new DispatchProperties());
> Maybe we should do that validation in `DispatchProperties`?

I'm not sure I understand

2021-02-03 09:10 UTC, tmasternak commented on src/Transport/AzureStorageQueueTransport.cs
> +        public AzureStorageQueueTransport(string connectionString, bool disableNativeDelayedDeliveries = false)
It turns out that Core depends on the value of the second parameter early on in setting up the endpoint e.g. throw if the transport does not declare to support delayed delivery and a user tries to send a delayed message. 

We need to keep this parameter as is to make sure the Core configuration works as expected.

2021-02-03 09:12 UTC, tmasternak commented on src/Transport/DelayDelivery/DelayedMessageEntity.cs
> +            return new UnicastTransportOperation(new OutgoingMessage(MessageId, Deserialize<Dictionary<string, string>>(Headers), Body), Destination, new DispatchProperties());
Nevermind. I miss read the `TODO` and thought it's a question about `DispatchProperties` and not `DispatchConsistency`.

2021-02-03 09:12 UTC, tmasternak approved these changes

2021-02-03 14:11 UTC, timbussmann reviewed
we should really replace all those `UseTransport` usages in the test.

2021-02-03 14:11 UTC, timbussmann commented on src/Transport/Config/WellKnownConfigurationKeys.cs
>              public const string TableName = "Transport.AzureStorageQueue.TableName";
what is this one still used for?

2021-02-03 14:11 UTC, timbussmann commented on src/Transport/DelayDelivery/DelayedMessageEntity.cs
> +            return new UnicastTransportOperation(new OutgoingMessage(MessageId, Deserialize<Dictionary<string, string>>(Headers), Body), Destination, new DispatchProperties());
technically this could become an issue if there are more dispatch properties added that are expected to be taken into account when delaying a message?

2021-02-03 14:11 UTC, timbussmann commented on src/Transport/DelayDelivery/DelayedMessagesPoller.cs
> +            //TODO does this need to set the FailedQ header and the failure reason?
remaining todo

2021-02-04 10:20 UTC, mauroservienti commented on src/Transport/AzureStorageQueueTransport.cs
> +            // TODO: why were settings merged?
OK, thanks. We can't do that anymore because by the time they are here they are read-only and merging throws.

2021-02-05 08:58 UTC, mauroservienti commented on src/Transport/Config/WellKnownConfigurationKeys.cs
>              public const string TableName = "Transport.AzureStorageQueue.TableName";
leftover

2021-02-05 09:01 UTC, mauroservienti commented on src/Transport/DelayDelivery/DelayedMessagesPoller.cs
> +            //TODO does this need to set the FailedQ header and the failure reason?
I added it, I have no idea if the fact that previously was not added was a bug.

2021-02-05 09:02 UTC, mauroservienti commented on src/Transport/DelayDelivery/DelayedMessagesPoller.cs
> +            //TODO does this need to set the FailedQ header and the failure reason?
> technically this could become an issue if there are more dispatch properties added that are expected to be taken into account when delaying a message?

Good question, no idea 😄

2021-02-05 09:07 UTC, mauroservienti commented on src/Transport/AzureStorageQueueTransport.cs
> +        static MessageWrapperSerializer BuildSerializer(SerializationDefinition userWrapperSerializationDefinition, ReadOnlySettings settings)
They weren't null before. Fixed now.

2021-02-08 08:08 UTC, mauroservienti commented on src/Transport/DelayDelivery/DelayedMessageEntity.cs
> +            return new UnicastTransportOperation(new OutgoingMessage(MessageId, Deserialize<Dictionary<string, string>>(Headers), Body), Destination, new DispatchProperties());
Yes, that's correct @timbussmann. Since it was an issue before and not something introduced by the new seam I'm inclined to leave the TODO there and raise a follow-up issue.

2021-02-08 08:24 UTC, timbussmann commented on src/Transport/DelayDelivery/DelayedMessageEntity.cs
> +            return new UnicastTransportOperation(new OutgoingMessage(MessageId, Deserialize<Dictionary<string, string>>(Headers), Body), Destination, new DispatchProperties());
maybe we can update the TODO comment to be a bit easier to understand in the context of the new seam and the DispatchProperties?

2021-02-11 16:06 UTC, SeanFeldman commented
@mauroservienti, should I hold off with the review given the PR is still a draft and changes are taking place?

2021-02-11 16:12 UTC, mauroservienti commented
> @mauroservienti, should I hold off with the review given the PR is still a draft and changes are taking place?

No @SeanFeldman, my mistake. I was fighting with some API changes in the latest Core bits and I also forgot about making this ready for review. Please, go ahead.

2021-02-16 23:02 UTC, SeanFeldman submitted a review, later dismissed

2021-02-17 14:33 UTC, mauroservienti commented on src/Transport/DelayDelivery/NativeDelayDeliveryPersistence.cs
> +    class NativeDelayDeliveryPersistence
The new name is due to the fact that the original `NativeDelayDelivery` class has been split, for initialization/dependencies reason into `NativeDelayDeliveryPersistence` which tasks care of storing the delayed message, and `NativeDelayDeliveryProcessor` which is responsible to process expired delayed messages. I'm open to a better name proposal for `NativeDelayDeliveryPersistence` if it makes sense.

2021-02-17 14:34 UTC, mauroservienti commented on src/AcceptanceTests/EndpointConfigurationExtensions.cs
> +            //TODO this is kind of a hack because the acceptance testing framework doesn't give any access to the transport definition to individual tests.
I'm planning to raise follow-up issues for any of the unresolved TODOs. Once the issue is created I'll link to the issue in the comment and remove the TODO

2021-02-17 14:35 UTC, mauroservienti commented
I should have addressed all the relevant comments @SeanFeldman

2021-02-18 04:32 UTC, SeanFeldman commented
> I should have addressed all the relevant comments @SeanFeldman

Almost. There are a couple of minor ones that were missed out. `ProviderProvider`  and a TODO that is more of a comment rather than a TODO. Aside from that, the rest is 👍

2021-02-20 17:20 UTC, SeanFeldman commented on src/Transport/DelayDelivery/DelayedMessagesPoller.cs
> +            //TODO does this need to set the FailedQ header and the failure reason?
Addressed in a separate PR, no?

2021-02-20 17:20 UTC, SeanFeldman commented on src/Transport/AtLeastOnceReceiveStrategy.cs
> +                //TODO: what this should look like given the new cancellation support?
Should this link back to the raised issue?

2021-02-20 17:20 UTC, SeanFeldman commented on src/Transport/AtLeastOnceReceiveStrategy.cs
> +                var pushContext = new MessageContext(message.Id, new Dictionary<string, string>(message.Headers), body, new TransportTransaction(), new ContextBag());
Can be resolved when the comment below is.

2021-02-22 11:21 UTC, timbussmann commented on src/Tests/ApprovalFiles/APIApprovals.ApproveAzureStorageQueueTransport.approved.txt
> -        public AzureStorageQueueTransport() { }
do we have to obsolete the parameterless ctor instead? 🤔

2021-02-22 11:21 UTC, timbussmann commented on src/Transport/Config/Extensions/AccountRoutingSettings.cs
> +        /// Get or set default account alias.
```suggestion
        /// Get or set the default account alias.
```

2021-02-22 11:21 UTC, timbussmann commented on src/Transport/Config/Extensions/AccountRoutingSettings.cs
> +        string _defaultAccountAlias = string.Empty;
remove the `_` :P

2021-02-22 11:21 UTC, timbussmann commented on src/Transport/DelayDelivery/DelayedMessageEntity.cs
> +            return new UnicastTransportOperation(new OutgoingMessage(MessageId, Deserialize<Dictionary<string, string>>(Headers), Body), Destination, new DispatchProperties());
I guess technically this class should store the dispatch properties and rehydrate them but given it didn't store the delivery constraints before, this isn't quite necessary atm (but might become an issue later). Is that something that is worth being documented as a constraint/cruft?

2021-02-22 11:21 UTC, timbussmann commented on src/Transport/DelayDelivery/NativeDelayDeliveryPersistence.cs
> +        NativeDelayDeliveryPersistence()
can you have default values on ctor parameters? might make this a bit more readable.

2021-02-22 11:21 UTC, timbussmann commented on src/AcceptanceTests/TestSuiteConstraints.cs
> +        public bool SupportsPurgeOnStartup => false;
but it seems to support it, doesn't it?

2021-02-22 11:21 UTC, timbussmann commented on src/Transport/obsoletes-v11.cs
> +            Message = "Account aliases using connection strings have been deprecated. Use the AddCount overload that accepts a QueueServiceClient instance.",
```suggestion
            Message = "Account aliases using connection strings have been deprecated. Use the AddAccount overload that accepts a QueueServiceClient instance.",
```

2021-02-24 08:43 UTC, mauroservienti commented on src/Tests/ApprovalFiles/APIApprovals.ApproveAzureStorageQueueTransport.approved.txt
> -        public AzureStorageQueueTransport() { }
I don't think so, there was no use case for users' usage of that constructor, right?

2021-02-24 09:00 UTC, mauroservienti commented on src/AcceptanceTests/Sending/When_replying_to_a_message_with_reply_to_header_containing_connection_string.cs
> +                    var receiverAccountInfo = transport.AccountRouting.AddAccount(ReceiverAlias, Utilities.GetEnvConfiguredConnectionString2());
rewrite using the non-obsoleted API. Does it make sense to do it now?

2021-02-24 10:52 UTC, timbussmann commented on src/Tests/ApprovalFiles/APIApprovals.ApproveAzureStorageQueueTransport.approved.txt
> -        public AzureStorageQueueTransport() { }
yeah that's true 👍

2021-02-24 10:53 UTC, timbussmann commented on src/AcceptanceTests/Sending/When_replying_to_a_message_with_reply_to_header_containing_connection_string.cs
> +                    var receiverAccountInfo = transport.AccountRouting.AddAccount(ReceiverAlias, Utilities.GetEnvConfiguredConnectionString2());
either that or adding separate tests using the new API so we have both as long as you can use both APIs

2021-02-26 10:50 UTC, timbussmann approved these changes

2021-02-26 11:00 UTC, merged